language: go
go:
  - "1.11"

services:
  - postgresql

env:
  - POSTGRES_USER=postgres POSTGRES_HOST=localhost POSTGRES_DB=golangdb POSTGRES_DB_PORT=5432 DEFAULT_ADMINISTRATOR_ROLE=ADMINISTRATOR DEFAULT_JWT_SIGNING_KEY=lkjsd3834#44wsdkfsd&%dslkfdlfk2338fjdidu%$#ASfsdfkj DEFAULT_ADMIN_EMAIL=root@golang.com DEFAULT_ADMIN_FULL_NAME=root DEFAULT_ADMIN_NICK_NAME=root DEFAULT_ADMIN_PASSWORD=golangiscool

before_script:
  - psql -c 'create database golangdb;' -U postgres

script:
  - cd app/
  - ./run-test.sh