language: go

before_install:
  - cat /etc/os-release
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce

script:
  - sudo docker run hello-world
  - cd app/